SwaprHQ/presagio

- app/components/CardBet.tsx
- app/components/ConfirmTrade.tsx
- app/components/Swapbox.tsx
- app/components/TransactionModal.tsx
- app/components/UserBets.tsx
- context/ModalContext.tsx
- context/TxContext.tsx
- context/index.ts
- providers/providers.tsx
this provider wraps wagmi's `writeContract` method with the `TransactionModal` to show feedback from the written transaction: loading/success/error and also links to explorer.
**API**
`submitTx` - call writeContract, shows modal with tx
**TransactionModal**
Modal with transaction feedback 
- tx state: loading/success/error
- tx explorer link
> Add TxContext to abstract writeContract with TX modal - submitTx

- app/page.tsx
- queries/omen/markets.ts
This PR takes care of the initial functionality of categories. 
It allows filtering markets by a category at a time.
The design from Akash uses Tabs component but Tabs implies that we render content related to the tab, in this case we just want to choose an option from several options which is our `ToggleGroup` component does. 
So we'll go with that and then we can add a diff component to swapr-ui or just have diff design option to ToggleGroup, we should explore options.
**Current design**
> Allow filtering markets by categories (functionality)

- app/markets/MarketDetails.tsx
Add the initial tabs for switching "bet" and "history".
This will use the component ToggleGroup, which reflect the design. In the near future we should add this design to Tabs as well.
> on MarketDetail add ToggleGroup to change between "Bet" and "history"

- app/components/ui/Table.tsx
- app/markets/ActivityTable.tsx
- app/markets/HistorySection.tsx
- utils/dates.ts
- utils/index.ts
- utils/token.ts
This is only the UI for activity
Uses [Shadcn Table](https://ui.shadcn.com/docs/components/table) table component
Added 2 utils functions to help make things more readable:
- `formatDateTime`
- `shortenAddress`
few comments:
- data is mocked
- will not attempt to show avatar based on address at this time.
- Detect AI will come later
- pagination will come later
> Show activity on Market - list of user trades  (UI)

- app/components/Swapbox.tsx
* Update the minimum height for the balance tile in the Swapbox component
> [PGIO-46][FIX] - Flip button not centered when flipped inputs

- app/markets/ActivityTable.tsx
- queries/omen/markets.ts
- queries/omen/types.ts
* Updates the market `ActivityTable` component to display the traded outcome as an activity action instead displaying the transaction type.
> [PGIO-53][FEAT] - Improve actions in the Market activity table

- app/components/CardMarket.tsx
- app/components/OutcomeBar.tsx
**Update**
Following Leo advise, I think we can ditch the loading completely. As it seems to load instantly, also if does not have percentages it displays 50/50 (green/red).  I think it's works better and feels faster.
**Previous**
We already have the percentages so we can show the loading with the correct width (or if we don't we show 50/50) it mimics better the "success" outcome.
Also since the styles are almost the same, and by having a loading we can simplify a bit the code too.
Check the preview to feel it.
**Sample**
https://github.com/user-attachments/assets/9daa6ca8-3bc5-46fa-a310-b99bfc7ee867
**Previously**
https://github.com/user-attachments/assets/b4d0524c-3fca-47eb-a019-1d9fd5386b34
> remove outcome loading bar

- app/markets/page.tsx
Market id isn't case sensitive anymore.
> fix: market id should be lowercase

- app/page.tsx
Currently it keeps the page, so if you are on the third page of the "all" you change to crypto and it queries for third page which is empty.
Whenever a category is changed it page should be reset it.
eg:
Issue: https://linear.app/swaprhq/issue/PGIO-78/changing-category-on-a-tab-should-reset-page-to-1
> fix: page should be reset to 1 when category is changed

- app/filters.tsx
- queries/omen/markets.ts
Hey, small fix, please.
Currently, `Closing soon` is done as a filter for opening time <24 hours from now. The issue there is that:
1. These markets have usually withdrawn liquidity, which makes them as good as closed for the user of Presagio.
2. There is no guarantee that there will be any markets closing in less than X hours + having liquidity.
In PMAT library, we solve this by doing `Closing soon` by ordering them by `openingTimestamp ASC` + filtering for `openingTimestamp_gt>now` and `liquidity>0`. 
That's what I propose in this PR:
> Fix closing soon search

- app/components/CardBet.tsx
- app/components/Swapbox.tsx
- app/components/UserBets.tsx
- app/markets/ActivityChart.tsx
- app/markets/Bet.tsx
- app/markets/Info.tsx
- app/markets/MarketDetails.tsx
- app/my-bets/page.tsx
- entities/markets/index.ts
- entities/markets/market.ts
- entities/markets/marketCondition.ts
- entities/markets/trade.ts
- queries/conditional-tokens/queries.ts
- rename market to a more specific name: FixedProductMarketMaker
- fixes bug CardBet showing redeem button when already claimed
- on Market ententy rename market to fpmm
- add new entity MarketCondition to handle condition related like canRedeem, canClaim
- remove those methods from market
- refactor UserBets to use tradesCollateralAmountUSDSpent
- extract getOutcomeUserTrades to Trade entity
- improves names
- add id to position on Omen Markets query
> Improve redeemed related logic

- app/filters.tsx
- queries/omen/markets.ts
I'm currently working on a `challenger agent`, it's supposed to challenge questions on Reality, and I was missing this filter.
In the current version, there is no way to search for a market that is answered but not yet finalized.
The `Pending` filter is great, but that will show only markets without any answer on Reality.
Current dev:
Local test:
Reality:
> Add finalizing filter

- app/page.tsx
- constants/index.ts
- queries/dune/queries.ts
* Creates a way to query Dune dashboards to fetch our market categories sorted by "popularity", meaning, the number of markets in each category.
> [PGIO-85][FEAT] - dynamically fetch categories from Dune

- app/components/CardBet.tsx
- app/components/UserBets.tsx
- hooks/contracts/conditionalTokens.ts
**Description** 
As we currently only support 2 outcomes we can hardcode the indexSetOptions to [1,2] _(indexSet starts on 1 instead of 0, on Conditional Token contract)_ so we don't need to pass it on `redeemPositions` function. On the contract level it will check both outcomes and withdraw the correct one. We can think of a robust solution when we allow more options.
Closes #97
Closes #98 
Thanks @greenlucid for the issue report and PR.
**Summary** 
- adds indexSetOptions type
- adds default value to outcomeIndexOptions
- remove outcomeIndex argument on redeemPositions function
**How to test**
- try redeeming positions on "My bets" list
- try redeeming positions on a market
**screenshots**
meant to show where to test, those "redeem" buttons 
"My bets" list
Market
> Update redeemPositions contract function with a fixed set of outcomeIndexOptions

- app/components/CardBet.tsx
- app/components/TransactionModal.tsx
- app/components/UserBets.tsx
- context/TxContext.tsx
**Description**
New PR this fixes the problems we were having when clicking "redeem" on "My bets list" and "Market" views.
The problem was the loading modal was not showing and the success modal was triggered on click.
Now it should show proper loading tx modal and then on success it shows the green tick.
One of the problems was that we were using TxProvider which adds a `TransactionModal` component to the tree and we added another ones on `CardBet` and `UserBets` components, so when triggering openModal, there were 2 modals opening. Also some conditions on the modal needed extra checks.
This PR fixes those issues by making TxProvider more flexible by having 2 functions:
- `submitTx` (which receives the args and calls a write contract function from `wagmi`)
- `submitCustomTx` (which …
> Fix: On redeem was triggering TransactionModal Success straight way without completing and loading

- app/filters.tsx
- entities/markets/market.ts
- queries/omen/markets.ts
- utils/time.ts
Yesterday, I created this market for some debugging: https://presagio.pages.dev/markets?id=0x0129d8d46e5869D10956BECf8E4A793309B04909
It's special because finalization period was only 1 hour.
On Presagio, it's still shown in Finalizing filter:
And in the detail it also says I can still challenge it:
This is because there is hard-coded 24h finalization period in the code, this PR is fixing that.  🙏 
On localhost in this branch:
(this is bugged on this special market only atm, but we are going to change finalization period from 1 day to 3 days and then it would be bugged everywhere: https://github.com/gnosis/prediction-market-agent-tooling/pull/466)
> Don't hardcode 24h finalization

- queries/omen/markets.ts
This will enable the agents to create a test category meant for testing markets that will not appear on all markets but can still be filtered.
> filter "test" market category when no category is passed

- app/(main)/markets/Bet.tsx
- app/(main)/markets/MarketActivity.tsx
- app/components/CardBet.tsx
- constants/index.ts
- entities/markets/market.ts
Example profile: https://feat-pgio-107-show-outcome-s.presagio.pages.dev/profile?address=0x91fEA319Ed45c7b12683c8c25e741151fBFee24b
Closes #126
> feat: show market status and winning outcome on cardbet

- app/(main)/markets/MarketDetails.tsx
- app/(main)/markets/MarketNotFound.tsx
- app/(main)/markets/page.tsx
Currently we are returning null if search params address is null or corrupt. Which just displays an empty interface.
Showing market not found is a better experience.
> Show market not found if search params address is corrupt or not passed

- queries/omen/markets.ts
* Adds "Jobs" category to the filter list to hide markets when displaying the All category.
https://www.loom.com/share/280026a67ae34b13b7e5087986bcf9f9?sid=9638d240-8a62-4f20-88e0-7593b7c954b7
> [FEAT][PGIO-132] - Hide Jobs markets from All category

- app/components/OutcomeBar.tsx
* Updates the `OutcomeBar` component logic to use `marketModel.isAnswerInvalid` (from the subgraph) instead of negating the result from `marketModel.getWinnerOutcome()`
> fix(PGIO-139): use isAnswerInvalid for checking if the market is invalid

- app/(main)/markets/MarketDetails.tsx
> fix: market tabs overflowing on mobile

- analytics/index.ts
- app/(main)/MarketsHighlight.tsx
- app/(main)/page.tsx
- app/components/MarketThumbnail.tsx
Since we already have some ranking and the first 12 markets should be the best in terms of liquidity and betting activity, we can randomly highlight the markets, since it makes the page more interesting.
**preview**
> Use the MarketsHighlight component to highlight 3 markets and make landing more interesting
