SwaprHQ/presagio

app/components/Swapbox.tsx, app/components/ui/SwapInput.tsx, app/globals.css
=> feat: create swapbox input

app/components/CardMarket.tsx, app/components/ui/Navbar.tsx, app/layout.tsx, app/markets/[id]/error.tsx, app/markets/[id]/page.tsx
In this way it does not change the sizes of tailwind and we can expect them as default.
=> Set font size as class at body tag

app/components/CardBet.tsx, app/components/ui/Footer.tsx, app/my-bets/page.tsx, app/page.tsx, codegen.ts, constants/index.ts, models/Market.ts, models/Position.ts, models/index.ts, queries/conditional-tokens/index.ts, queries/conditional-tokens/queries.ts, queries/conditional-tokens/types.ts, queries/omen/markets.ts, queries/omen/types.ts, utils/dates.ts
**summary**
- fetch market data for position on BetCard 
- add queries for conditionals tokens subgraph
- fetch data from conditionals token subgraph
- update my bets page to fetch userPositions data
- add subgraph urls from constants
Out of scope:
- outcome amount calculations
- correct answer
=> My bets data

queries/omen/markets.ts
- Adds fetching markets with only binary outcomes
=> feat: only fetch binary markets

app/components/OutcomeBar.tsx, app/components/SettingsPopover.tsx, app/components/ui/SwapInput.tsx, entities/outcome.ts, hooks/useShowClientUI.tsx
- Improves Market outcome redability
- Fixes SettingsPopover hydratation problem
=> fix: improve market outcome readability

app/components/CardBet.tsx, app/components/ConfirmTrade.tsx, app/components/Swapbox.tsx, app/components/TransactionModal.tsx, app/components/index.ts, app/markets/MarketDetails.tsx, model/conditionalTokens.ts, queries/conditional-tokens/queries.ts
- Add logic to redeem won bets
- Control if bet was already redeemed
=> feat: logic to redeem won bets

app/components/CardBet.tsx, app/components/Swapbox.tsx, app/markets/MarketDetails.tsx, queries/conditional-tokens/queries.ts
=> feat: bet and win amount on bet card

app/components/OutcomeBar.tsx, app/components/Swapbox.tsx, app/markets/MarketDetails.tsx, entities/outcome.ts, model/market.ts, models/Market.ts, queries/conditional-tokens/queries.ts, queries/omen/markets.ts
=> feat: finished bet state on market detail

app/components/UserBets.tsx, app/components/index.ts, app/markets/MarketDetails.tsx
- Shows user bets on market detail
- Allows bet claiming inside market detail
=> feat: improve market user bets

app/components/CardMarket.tsx, app/components/SettingsPopover.tsx, app/page.tsx, hooks/index.tsx, hooks/useDebounce.tsx, queries/omen/markets.ts
=> feat: add search and filtering on markets page

app/components/CardBet.tsx, app/my-bets/page.tsx, entities/markets/market.ts, entities/markets/trade.ts
Description
- add unredeemed tab
- Also fixes bug not showing correct color when `isLoser`
=> Add unredeemed bets tab functionality

app/page.tsx
Add filters to searchParams, this keeps the filters state on the url, it allows keeping the state on refresh and is sharable.
Add search to search params
=> add filters & search to searchParams

app/components/Swapbox.tsx, app/components/ui/SwapInput.tsx, app/markets/MarketDetails.tsx, app/my-bets/page.tsx, app/page.tsx
=> feat: add pagination on markets page

app/layout.tsx
Makes font less bold
**with antialiased**
**without**
=> set font Smoothing with antialiased

app/page.tsx
=> Add category to SearchParams

app/markets/HistorySection.tsx, app/markets/MarketDetails.tsx, app/my-bets/page.tsx
=> Add tab to switch between activity and chart

app/filters.tsx, app/page.tsx, queries/omen/markets.ts
- Adds filter by market state. Created new queries for each diff state query.
- Adds new order filter.
=> feat: add filter market by state

app/components/SettingsPopover.tsx, app/components/ui/SwapInput.tsx, app/page.tsx
* Adds `asChild` prop to `PopoverTrigger` components
=> [FIX] - Nested buttons error

app/filters.tsx, app/page.tsx, queries/omen/markets.ts
- Add creator filters
- Update logic to use different search params on the query
=> feat: enable all markets

app/markets/ActivityTable.tsx, app/markets/HistorySection.tsx, app/markets/MarketDetails.tsx, queries/omen/markets.ts, utils/currencies.ts, utils/dates.ts, utils/token.ts
- add the graph query
- add table component
- add table loading
- gnosisExplorerAddress to utils token
**preview**
In following PRs we'll add:
- pagination
- small design improvements
=> Add activity table to market details

app/markets/ActivityTable.tsx, app/markets/HistorySection.tsx, queries/omen/markets.ts
=> feat: add pagination to activity table

app/components/OutcomeBar.tsx
* `isLoading` variable was not refreshing correctly
=> [FIX] - OutcomeBar not loading correctly

app/markets/MarketDetails.tsx, app/markets/News.tsx
=> feat: add news to market details

app/markets/MarketDetails.tsx, entities/markets/market.ts
=> feat: disable swapbox when market has no liquidity

app/components/CardBet.tsx, app/components/ui/images/NoBetsImage.tsx, app/my-bets/page.tsx, queries/conditional-tokens/queries.ts, utils/dates.ts
Sorts my bets (userPositions) by position created timestamp.
This lead to a refactor on how we fetch data, we also need to merge all data into an array to be able to sort it properly.
there are still some type issues that I'll fix.
=> sort userPositions on My bets page

app/components/ui/SwapInput.tsx
=> fix token input outside of area

app/components/CardBet.tsx, app/components/ConfirmTrade.tsx, app/components/Swapbox.tsx, app/components/UserBets.tsx, utils/currencies.ts
improve formatEtherWithFixedDecimals to fix showing 0.000 on very small numbers
Now it shows `<0.001`
=> [fix] bug showing 0.000 on very small numbers

app/components/CardBet.tsx, app/my-bets/page.tsx, entities/markets/market.ts, entities/markets/outcome.ts, entities/markets/position.ts
- fixes a false positive
- improves names
- update Position model (add, id, condition, getOutcomeIndex)
- update Market model ( add canClaim)
=> [My bets] update filter unredeemed and related logic

app/components/BetsListPanel.tsx, app/components/CardBet.tsx, app/my-bets/page.tsx, app/profile/page.tsx, entities/markets/index.ts, entities/markets/userBets.ts, queries/omen/markets.ts
UserPositionComplete is not a good name, what is complete?
This PR aims to improve the name abstraction.
- create UserBet entity
=> rename UserPositionComplete to UserBets

app/components/SettingsPopover.tsx, app/profile/page.tsx, queries/mobula/index.ts, queries/mobula/queries.ts
Fetches token USD prices to show accurate user betting stats.
=> feat: fetch collateral token USD price

app/components/SettingsPopover.tsx, app/filters.tsx, app/markets/Bet.tsx, entities/markets/market.ts, queries/omen/markets.ts, utils/index.ts, utils/time.ts
=> feat: show if current answer is not resolved

hooks/useAnalytics.tsx
=> fix: window error on analytics and improve url

app/page.tsx, queries/omen/markets.ts
=> add ability search for addresses

app/components/Swapbox.tsx
=> feat: add bet potential profit

app/filters.tsx, app/page.tsx
=> feat: swap default market creator order

app/components/CardBet.tsx, app/components/CardMarket.tsx, app/components/Skeleton.tsx, app/components/index.ts, app/markets/ActivityChart.tsx, app/markets/MarketActivity.tsx, app/markets/MarketDetails.tsx, app/markets/News.tsx, app/profile/page.tsx
* Abstracts common "loading" styles and structure into a Skeleton component
* Replace the repeated styles with the new Skeleton
* Minor helper components renaming for consistency's sake
=> [PGIO-65][FEAT] - Create Skeleton component that abstracts styles

app/markets/Bet.tsx, entities/markets/market.ts, providers/providers.tsx
Invalid market while answer is finalizing
https://feat-pgio-80-fix-winner-stat.presagio.pages.dev/markets?id=0xb5836a387d5e09d8bac507c5d6cefe0722f7d8f4
Invalid market when answer is final
https://feat-pgio-80-fix-winner-stat.presagio.pages.dev/markets?id=0x12a8b2972b5dec1781b56e535aa0814d64fa2527
=> feat: add invalid state on market details

app/filters.tsx, app/page.tsx, constants/index.ts, queries/omen/markets.ts
=> Add collateral token filters

app/components/CardBet.tsx, app/components/UserBets.tsx
=> fix: redeem will be called with position collateral

app/MarketsHighlight.tsx, app/markets/MarketActivity.tsx, queries/omen/markets.ts
=> fix: show market creator instead of fpmm contract on market activity

app/components/Swapbox.tsx
Cleans up the swapbox after a swap
=> reset swapbox after a swap

app/(main)/filters.tsx
=> fix: improve token filter names

app/(main)/profile/page.tsx, app/components/CardBet.tsx, app/components/CardMarket.tsx, app/components/UserBets.tsx, entities/markets/trade.ts
- fixes sdai markets showing 0 by showing collateral raw amount instead of usd amount
- fixes sdai bets not appearing on market details
- improves metrics displayed on profile page
=> fix: sdai markets have 0 value

app/(main)/markets/MarketDetails.tsx
* Redirects to the home page if there's no browser history on the market back button
https://www.loom.com/share/343257a114a9417d83cdf719bfc12f3f?sid=599df88b-6c8f-4918-9c4c-6bdc7e536e01
=> [FIX][PGIO-91] - Back button looks broken

app/(main)/markets/News.tsx, app/components/CardBet.tsx, app/components/UserBets.tsx, entities/markets/marketCondition.ts, entities/markets/trade.ts, queries/conditional-tokens/queries.ts
=> feat: allow users to redeem positions from invalid markets

app/components/Footer.tsx, app/components/MadeBySwapr.tsx, app/components/Navbar.tsx, constants/index.ts, tailwind.config.ts
Add a better footer
**features**
- show partners that help power Presagio
- show socials
- show market categories
**Screenshots**
=> Add new footer

app/components/ConfirmTrade.tsx, app/components/TransactionModal.tsx, app/layout.tsx, providers/providers.tsx
https://github.com/user-attachments/assets/4d0b31b1-b5e9-4917-a4f8-e7ce13572d73
=> feat: improve tx creation experience

app/components/ConfirmTrade.tsx, app/components/Swapbox.tsx, app/components/TransactionModal.tsx, context/SlippageContext.tsx, context/index.ts, providers/providers.tsx
- Allows user to update slippage. 
- New default slippage is 0.01%.
=> feat: editable slippage

app/(main)/profile/page.tsx
=> fix: profile page bets loading

app/(main)/markets/MarketDetails.tsx
=> category should be clickable and filter per category

app/components/Swapbox.tsx
=> increase font weight on the Swapbox

abi/index.ts, app/(main)/markets/Liquidity.tsx, app/(main)/markets/MarketDetails.tsx, app/(main)/markets/UserLiquidity.tsx, app/components/ConfirmTrade.tsx, app/components/NetworkButton.tsx, app/components/Spinner.tsx, app/components/Swapbox.tsx, app/components/TransactionModal.tsx, app/components/index.ts, app/components/toasts.tsx, app/components/ui/SwapInput.tsx, context/ModalContext.tsx, hooks/contracts/erc20.ts, hooks/index.tsx, hooks/useUnsupportedNetwork.tsx, queries/omen/dangerousKeywords.ts, queries/omen/markets.ts, utils/liquidity.ts
Enables users to add and remove liquidity from markets.
=> feat: add and remove liquidity from market

app/(main)/markets/Info.tsx, app/(main)/profile/page.tsx, app/components/TransactionModal.tsx, app/components/toasts.tsx, utils/token.ts
* Creates a utils function to get the explorer URL for TXs and addresses
* Cleans the now unneeded old functions
=> chore(PGIO-119): Create function to return explorer link

app/components/ConnectButton.tsx
- use Avatar component
- display ens name when available
Without ens
=> Fix: ConnectButton not showing ens name or avatar

app/(main)/my-bets/page.tsx, entities/markets/userBets.ts
We need quick filters to see won or lost bets, this PR adds support for that.
=> Add filters for won/lost bets on "My Bets"

app/(main)/markets/MarketDetails.tsx, app/(main)/markets/News.tsx, queries/gnosis-ai/queries.ts
- Market insights endpoint will accept questions instead of market id
=> feat: update market insights endpoint

app/(main)/markets/AiChat.tsx
=> make wizard better on mobile

app/(main)/markets/AiChat.tsx, app/components/ui/ScrollArea.tsx
This PR adds scroll to bottom functionality, anytime you open a chat it will have messages scrolled down.
=> scroll down chat messages to bottom

app/(main)/leaderboard/agents/AgentsLeaderboardTable.tsx, queries/dune/queries.ts
Adds search filter support for address and labels to agents leaderboard
=> Add search filters for address/label on Dune query

app/(main)/markets/AiChat.tsx
- Show confidence and outcome on chatbot
=> feat: show confidence and outcome on chatbot

app/(main)/leaderboard/agents/AgentsLeaderboardTable.tsx, queries/dune/queries.ts
- add ROI support on Dune (https://dune.com/queries/4565681)
=> Adds ROI column to agents leaderboard table

queries/conditional-tokens/queries.ts
For eg for 500 positions
on 100 positions
=> increase number of user position we fetch

app/(main)/markets/AiChatMarket.tsx
- Calls the prediction endpoint to create and retrieve market predictions
=> feat: add predictions on market details

app/(main)/leaderboard/agents/AgentsLeaderboardTable.tsx
This PR is meant to make it more clear what is gnosis AI agent, so we link to their website.
=> improve AI agents table caption

app/components/ui/Sheet.tsx, app/components/ui/Sidebar.tsx
=> improve Sidenav toggle button

app/(main)/chat/Chat.tsx
=> feat: ai generated disclaimer

app/(main)/markets/MarketDetails.tsx
- Remove liquidity option when market is closed
=> fix: adding liquidity to closed market
